[tool.poetry]
name = "loki-test"
version = "0.1.0"
description = ""
authors = ["chengying <chengying@choirai.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
prometheus-client = "^0.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
